### ISSUE TITLE
Back button in Android does not work

### ISSUE THREAD

**Issue by freedumb2000** [mbaljeetsingh/ionic4-angular-news#1]
When compiling to an apk, the back button does not work on two android devices I have tried nor the emulator when trying to navigate back from /news-single. It works fine in Chrome on Linux and Chrome on Android.

**Comment by mbaljeetsingh** [comment]
@freedumb2000  try to add the following code in the news-single.html <ion-header>,
```
<ion-buttons slot="start">
    <ion-back-button></ion-back-button>
</ion-buttons>
```
